from typing import Any, Dict, List, Optional
import numpy as np
from llm_sdk import Small_LLM_Model
from .models import FunctionDefinition

_NUMBER_CHARACTERS = set("0123456789.- ")


class ParameterParser:
    """Fills a function's parameters by continuing a JSON object.

    A single header prompt describes the request and the function once.
    From there, the code writes the literal JSON skeleton
    (``{"name": ..., "parameters": {"key": ``) and only the value after
    each key is generated by the model, under a type-specific logit

    mask, before the code writes the next literal separator and key.
    """

    _BOOLEAN_CANDIDATES = ("true", "false")
    _OPENERS = "([{"
    _CLOSERS_TO_OPENERS = {")": "(", "]": "[", "}": "{"}

    def __init__(self, model: Small_LLM_Model) -> None:
        """Store the model and the per-run caches used for masking.

        Parameters
        ----------
        model:
            The language model used for both scoring and generation.
        """
        self._model = model
        self._token_cache: Dict[int, str] = {}
        self._number_token_ids: Optional[np.ndarray] = None
        self._string_token_ids: Optional[np.ndarray] = None

    def parse(
        self,
        prompt: str,
        function: FunctionDefinition,
    ) -> Dict[str, Any]:
        """Extract every parameter required by ``function`` from ``prompt``.

        Parameters
        ----------
        prompt:
            The natural-language user request.
        function:
            The function selected by the constrained decoder.

        Returns
        -------
        dict[str, Any]
            Every extracted parameter, converted to its declared type.

        Raises
        ------
        ValueError
            If a parameter type is unsupported or a value cannot be
            extracted or converted.
        """
        context = self._build_header(prompt, function)
        parameters: Dict[str, Any] = {}
        items = list(function.parameters.items())

        for index, (name, definition) in enumerate(items):
            param_type = definition.type
            context += f'"{name}": '

            if param_type == "boolean":
                raw_value = self._generate_boolean(context)
                context += raw_value
            elif param_type in ("number", "integer"):
                raw_value = self._generate_number(context, prompt)
                context += raw_value
            else:
                context += '"'
                raw_value = self._generate_string(context, prompt)
                context += raw_value + '"'

            if not raw_value:
                raise ValueError(
                    f"Unable to extract value for parameter {name!r}."
                )

            parameters[name] = self._convert(raw_value, param_type, name)

            if index < len(items) - 1:
                context += ", "

        return parameters

    def _build_header(self, prompt: str, function: FunctionDefinition) -> str:
        """Build the single shared prompt: function, request, and the
        literal JSON prefix the model is about to continue.
        """
        schema = ", ".join(function.parameters.keys())
        return (
            f"Function: {function.name} - {function.description}\n"
            f"Parameters: {schema}\n"
            f"Request: {prompt}\n\n"
            f'{{"name": "{function.name}", "parameters": {{'
        )

    def _generate_number(self, context: str, prompt: str) -> str:
        """Generate a numeric literal continuing ``context``."""
        prompt_len = len(prompt)
        allowed_ids = self._get_number_token_ids()
        return self._generate_constrained(context, allowed_ids, prompt_len)

    def _generate_string(self, context: str, prompt: str) -> str:
        """Generate a string's contents (without the wrapping quotes,
        which the caller adds) continuing ``context``."""
        prompt_len = len(prompt)
        allowed_ids = self._get_string_token_ids()
        return self._generate_constrained(context, allowed_ids, prompt_len)

    def _generate_boolean(self, context: str) -> str:
        """Pick whichever of 'true'/'false' scores higher as the next
        token -- with only two candidates, there's no need to mask a
        full vocabulary; just compare their two logits directly."""
        prompt_ids = self._model.encode(context)[0].tolist()
        logits = self._model.get_logits_from_input_ids(prompt_ids)

        first_token_of = {
            candidate: self._model.encode(candidate)[0].tolist()[0]
            for candidate in self._BOOLEAN_CANDIDATES
        }
        return max(first_token_of, key=lambda c: logits[first_token_of[c]])

    def _generate_constrained(
        self,
        context: str,
        allowed_token_ids: np.ndarray,
        max_tokens: int
    ) -> str:
        """Greedily generate a value continuing ``context``, one token
        at a time, taking the highest-scoring token that is allowed for
        this type.
        """
        value_text = ""
        allowed_set = set(int(i) for i in allowed_token_ids)

        for _ in range(max_tokens):
            prompt_ids = self._model.encode(context + value_text)[0].tolist()
            logits = np.array(
                self._model.get_logits_from_input_ids(prompt_ids)
            )

            best_overall = int(np.argmax(logits))

            masked = np.full(logits.shape, -np.inf)
            masked[allowed_token_ids] = logits[allowed_token_ids]
            best_allowed = int(np.argmax(masked))

            inside_bracket = self._has_unclosed_bracket(value_text)

            if best_overall not in allowed_set and not inside_bracket:
                break

            piece = self._token_text(best_allowed)

            if not piece:
                break

            value_text += piece

        return value_text.strip().strip(';')

    def _get_number_token_ids(self) -> np.ndarray:
        """Return (building and caching, on first use) every token id
        whose decoded text is made entirely of digits/'.'/'-'/space."""
        if self._number_token_ids is None:
            self._number_token_ids = self._build_allowed_ids(
                lambda text: all(ch in _NUMBER_CHARACTERS for ch in text),
            )
        return self._number_token_ids

    def _get_string_token_ids(self) -> np.ndarray:
        """Return (building and caching, on first use) every token id
        whose decoded text contains no newline or quote character."""
        if self._string_token_ids is None:
            self._string_token_ids = self._build_allowed_ids(
                lambda text: "\n" not in text and '"' not in text,
            )
        return self._string_token_ids

    def _build_allowed_ids(self, text_is_allowed: Any) -> np.ndarray:
        """Scan the vocabulary once and return every token id whose
        decoded text satisfies ``text_is_allowed``.
        """
        vocab_size = len(
            self._model.get_logits_from_input_ids(
                self._model.encode(" ")[0].tolist(),
            )
        )
        allowed_ids: List[int] = []

        for token_id in range(vocab_size):
            text = self._token_text(token_id)
            if text and text_is_allowed(text):
                allowed_ids.append(token_id)

        return np.array(allowed_ids)

    def _token_text(self, token_id: int) -> str:
        """Decode a single token id, caching the result for reuse."""
        cached = self._token_cache.get(token_id)

        if cached is None:
            cached = self._model.decode([token_id])
            self._token_cache[token_id] = cached

        return cached

    def _has_unclosed_bracket(self, text: str) -> bool:
        """Return True if ``text`` has an opening bracket with no match."""
        stack: List[str] = []

        for character in text:
            if character in self._OPENERS:
                stack.append(character)
            elif character in self._CLOSERS_TO_OPENERS:
                expected = self._CLOSERS_TO_OPENERS[character]
                if stack and stack[-1] == expected:
                    stack.pop()

        return bool(stack)

    def _convert(self, raw_value: str, param_type: str, name: str) -> Any:
        """Convert the generated text into the correctly typed value."""
        try:
            if param_type == "boolean":
                return raw_value == "true"
            if param_type == "integer":
                return int(float(raw_value.replace(" ", "")))
            if param_type == "number":
                return float(raw_value.replace(" ", ""))
            return raw_value.strip()
        except ValueError as exc:
            raise ValueError(
                f"Could not convert value {raw_value!r} for parameter "
                f"{name!r} to type {param_type!r}"
            ) from exc
